import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./Navbar/Navbar";

export const metadata: Metadata = {
  title: "Pokedex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="md:w-8/12 md:mx-auto">{children}</main>
      </body>
    </html>
  );
}
